### ISSUE TITLE
相对路径题目描述有误，与绝对路径题目相同

### ISSUE THREAD

**Issue by Cloud-Snow** [hust-open-atom-club/linux101-dojo-x64#5]
![image](https://github.com/user-attachments/assets/908b5acb-97c4-460b-b5e4-7fd03f3d0561)
![image](https://github.com/user-attachments/assets/f9d4692a-929a-4743-9d82-7d33c1f53a5b)

**Comment by mudongliang** [comment]
我来看看，是什么地方漏掉了相对路径的描述

**Comment by mudongliang** [comment]
https://github.com/pwncollege/linux-luminarium/blob/master/paths/relative-naked/DESCRIPTION.md

我们应该翻译的是这个内容，应该是挑战关卡源文件拷贝的时候忘记修改了

**Comment by mudongliang** [comment]
fixed in ffb02f9306eee1689578102472185fbf6d65ad6a
